### ISSUE TITLE
Remove 'tag' from json files for exported PDS definitions

### ISSUE THREAD

**Issue by chufe-dremio** [deane-dremio/dremio-cloner#33]
Remove 'tag' from json files for exported PDS definitions.
Currently, the tag for PDSs changes with every export which is problematic for CI/CD use cases.

![image](https://user-images.githubusercontent.com/85165302/234590220-c5430d30-24dc-4339-b3bf-39dd430f26ae.png)

**Comment by mxmarg** [comment]
Fixed https://github.com/deane-dremio/dremio-cloner/commit/18b6de56bf0fc97152d31d2ec4620c4d3eec00da
